name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v2
    - name: Git
      run: 'cd /var/www/html/test/deploytest && git pull'
